optionsFile: null
printHelp: false
# WebGoat libs
classPath :
  - WebGoat/BOOT-INF/lib
#  - /Users/yuntsy/My/Projects/Java/SpringTest/build/libs/BOOT-INF/lib
# appClass
appClassPath: [WebGoat/BOOT-INF/classes]
#appClassPath: [/Users/yuntsy/My/Projects/Java/SpringTest/build/classes/java/main]
mainClass:
inputClasses: []
javaVersion: 17
prependJVM: true
allowPhantom: true
worldBuilderClass: pascal.taie.frontend.soot.SootWorldBuilder
outputDir: output
preBuildIR: false
worldCacheMode: false
scope: APP
nativeModel: true
planFile: null
analyses:
  ir-dumper: ;
  routerAnalysis: ""
  beanAnalysis: ""
  cg: ""
  cfg: ""
  icfg: ""
  pta: "plugins:[org.example.spring.DICGConstructorPlugin]"
onlyGenPlan: false
keepResult:
  - $KEEP-ALL
